name: 3 Understanding Runners

on: push

jobs:
  runner-info:
    runs-on: ubuntu-latest

    steps:
      - name: Print Ubuntu Runner Details
        run: |
          echo "Workflow is executing on a Github-hosted runner."
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"
  windows-runner-info:
    runs-on: windows-latest
    steps:
      - name: Print windows Runner Details
        run: |
          echo "Workflow is executing on a Github-hosted windows runner."
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"
